path: /Users/agniaendie/IdeaProjects/YandexStudCamp/kaiv/datasets
  #C:\\Users\\tekma\\PycharmProjects\\YandexStudCamp\\datasets
train: merged_circles_boxes
  #train_dataset
val: eval_circles_boxes
  #eval_dataset

nc: 2
#circle
names: ['sphere', 'cube']